saba:
  appconfig:
    user: admin
    password: admin
    servers:
      server1:
        host: eureka1
        port: 8761

---

server:
  port: 0     
    
---

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      
      defaultZone: >-
        http://${saba.appconfig.user}:${saba.appconfig.password}@${saba.appconfig.servers.server1.host}:${saba.appconfig.servers.server1.port}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    preferIpAddress: false
              
---

spring:
  sleuth:
    sampler:
      percentage: 0.1
  banner:
    location: classpath:/saba-banner.txt      

---
   
spring:
  rabbitmq:
    host: localhost
    port: 5672
  zipkin:
    sender:
      type: rabbit
              
---

management:
  endpoints:
    web:
      exposure:
        include: info, health

---

spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    
---     

logging:
  level:
    ROOT: INFO    
