saba:
  appconfig:
    KEY_STORE_FILE: saba-jwt.jks
    KEY_STORE_PASSWORD: saba-pass
    KEY_ALIAS: saba-oauth-jwt
    JWK_KID: saba-key-id
    
---
    
logging:
  level: 
    org.springframework.security: DEBUG  

---

server:
  servlet:
    context-path: /uaa
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true 
    show-sql: true    
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true
    username: saba
    password: a+123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: validation
    
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-auth-server:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: a+123456