spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true 
    show-sql: true    
  datasource:
    url: jdbc:mysql://localhost:3306/productreviewdb?useSSL=false&allowPublicKeyRetrieval=true
    username: saba
    password: a+123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-product-review-service:3306/productreviewdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: a+123456